export default [
  [
    ['exciting', 'excited', 'wonderful', 'nice', 'joyful', 'gleeful', 'glee', 'blessed', 'delighted', 'smiling'],
    ['＾ω＾', '（＾∀＾）', '≧ω≦', '(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧', '(≧◡≦)'],
  ],
  [
    ['unhappy', 'depressed', 'depressing', 'depression', 'miserable', 'heartbroken', 'broken-hearted'],
    ['╥﹏╥', '(╥_╥)', '(⋟﹏⋞)', '༼ ༎ຶ ෴ ༎ຶ༽', '（>﹏<）', '（；＿；）'],
  ],
  [
    [
      'angery',
      'mad',
      'annoyed',
      'annoying',
      'hate',
      'rage',
      'quit',
      'ragequit',
      'fuck',
      'fucks',
      'fucked',
      'shit',
      'shitty',
      'shits',
      'bullshit',
      'motherfucker',
      'triggered',
    ],
    ['ಠ_ಠ', '⋋_⋌', 'ಠ▃ಠ', '(╬ಠ益ಠ)', '(¬_¬)', '（＞μ＜＃）', '凸ಠ益ಠ)凸', '(ノಠ益ಠ)ノ彡┻━┻'],
  ],
  [
    ['ez', 'easy', 'gg'],
    ['(⌐■_■)', '(ﾒ▼_▼)'],
  ],
  [
    [
      'love',
      'luv',
      'heart',
      'affection',
      'passion',
      'cute',
      'kawaii',
      'wife',
      'waifu',
      'husband',
      'husbando',
      'hasubando',
    ],
    ['(♥ω♥*)', '(｡♥‿♥｡)', 'ღゝ◡╹)ノ♡', '（♥￫ｏ￩♥）'],
  ],
  [
    ['boring', 'tired', 'tiring', 'exhausted', 'exhausting'],
    ['(￣Д￣', '（；￣д￣）', '（－－；', '（￣Ω￣）'],
  ],
  [
    ['hello', 'hewwo', 'welcome', 'youkoso'],
    ['ヾ(＾∇＾)', '( ﾟ▽ﾟ)/', '(=ﾟωﾟ)ﾉ', '(≧∇≦)/', 'ヾ(・ω・ｏ)', '( ^_^)／'],
  ],
  [
    ['lol', 'lul', 'xd', 'rofl', 'wofl', 'lmao', 'lmfao'],
    ['（ ´థ౪థ）', '( ◉◞౪◟◉)', '（ლ ^ิ౪^ิ）ლ', ';´༎ຶਊ ༎ຶ`;', '( ՞ਊ՞)'],
  ],
];
